version: '2'
services:
  photogallery:
    build: .
    command: bash -c "rm -f /photogallery/tmp/pids/server.pid || true && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/photogallery

  test-photogallery:
    build: .
    command: bundle exec rails t
    volumes:
      - .:/photogallery

  nginx:
    image: nginx
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - photogallery
    links:
      - photogallery:photogallery
