version: '2'
services:

  photogallery-dev:
    build: .
    command: bash -c "./start-dev.sh"
    ports:
      - 3000:3000
    volumes:
      - .:/photogallery

  photogallery:
    build: .
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - SECRET_KEY_BASE=[INSERT KEY]
    command: bash -c "./start-prod.sh"
    volumes:
      - .:/photogallery

  test-photogallery:
    build: .
    command: bundle exec rails t
    volumes:
      - .:/photogallery

  nginx:
    image: nginx
    volumes:
      - .:/photogallery
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - photogallery
    links:
      - photogallery:photogallery
