version: '2'
services:
  typeinstant:
    build: .
    command: bash -c "rm -f /typeinstant-sergio/tmp/pids/server.pid || true && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/typeinstant-sergio

  test-typeinstant:
    build: .
    command: bundle exec rails t
    volumes:
      - .:/typeinstant-sergio

  nginx:
    image: nginx
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - typeinstant
    links:
      - typeinstant:typeinstant
