version: '2'
services:
  photoblog:
    build: .
    command: bash -c "rm -f /photoblog/tmp/pids/server.pid || true && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/photoblog

  test-photoblog:
    build: .
    command: bundle exec rails t
    volumes:
      - .:/photoblog

  nginx:
    image: nginx
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - photoblog
    links:
      - photoblog:photoblog
