# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7980506f26c19cb25bba48469ae6e5e8654200e73430db91a883b17a5f54abe0d82d6aa5426b69920668ed42998b6c0b641d631d95f8aff98cb89d002a45612

test:
  secret_key_base: 8f6e1d64450d8c9fc4d2895a6bc4bd5a5f23c911e3c0059a4625b00494190f7afb150ef49916a385967d5834274b8db8981f4f008102b42e6678f74d3a4ddfae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
